"use client";

import { useMemo, useState, type ReactNode } from "react";
import { BookOpen, Headphones, MapPin, Search, Sparkles, Ghost, Baby, ChevronRight, Play, Clock3 } from "lucide-react";

type Story={title:string;subtitle:string;tag:string;audience:string;duration:string;accent:string;icon:ReactNode};
const stories:Story[]=[
{title:"The Night the Banyan Whispered",subtitle:"A north-Indian village legend about courage, rumours and the unknown.",tag:"Local Folklore",audience:"Teens + Adults",duration:"12 min",accent:"from-fuchsia-500/30 to-violet-500/10",icon:<Ghost className="h-5 w-5"/>},
{title:"Ganesha and the Moon",subtitle:"A playful mythology story, retold gently for younger listeners.",tag:"Mythology",audience:"Kids",duration:"8 min",accent:"from-amber-500/30 to-orange-500/10",icon:<Sparkles className="h-5 w-5"/>},
{title:"The First Sermon",subtitle:"A story-led introduction to Buddha's first teaching at Sarnath.",tag:"Sacred Story",audience:"All ages",duration:"15 min",accent:"from-cyan-500/25 to-sky-500/10",icon:<BookOpen className="h-5 w-5"/>},
{title:"The Honest Woodcutter",subtitle:"A classic moral tale with a choice at the end for children.",tag:"Moral Tale",audience:"Kids 7-12",duration:"6 min",accent:"from-emerald-500/25 to-teal-500/10",icon:<Baby className="h-5 w-5"/>}
];
const filters=["All","Hindu traditions","Buddhism","Jainism","Sikhism","Islam","Christianity","Judaism"];

export default function HomePage(){
const [filter,setFilter]=useState("All"); const [query,setQuery]=useState("");
const visible=useMemo(()=>{if(!query.trim())return stories;const q=query.toLowerCase();return stories.filter(s=>(s.title+" "+s.subtitle+" "+s.tag).toLowerCase().includes(q))},[query]);
return <main className="min-h-screen">
<nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-8"><div><div className="font-display text-xl font-semibold">Sacred Stories</div><div className="text-xs text-zinc-500">Read · Listen · Explore · Question</div></div><div className="hidden gap-6 text-sm text-zinc-400 md:flex"><a href="#stories">Stories</a><a href="#library">Library</a><a href="#places">Sacred Places</a><a href="#ai">Ask AI</a></div></nav>
<section className="mx-auto max-w-7xl px-5 pb-16 pt-8 md:px-8 md:pt-14"><div className="glass overflow-hidden rounded-[32px] p-7 md:p-12"><div className="max-w-4xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-amber-300/15 bg-amber-300/5 px-3 py-1 text-xs text-amber-200"><Sparkles className="h-3.5 w-3.5"/>A story-first sacred knowledge experience</div><h1 className="font-display text-4xl leading-tight md:text-6xl">Ancient words. Living stories. <span className="text-amber-300">Curious questions.</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-zinc-400 md:text-lg">Explore scripture, mythology, folklore, ghost stories, sacred places and timeless lessons — with separate views for children, families, learners and adults.</p><div className="mt-7 flex max-w-2xl items-center gap-2 rounded-2xl border border-white/10 bg-black/20 p-2"><Search className="ml-3 h-5 w-5 text-zinc-500"/><input aria-label="Search stories" value={query} onChange={e=>setQuery(e.target.value)} placeholder='Try "Krishna", "ghost stories", "Sarnath", "Ramayana"...' className="w-full bg-transparent px-2 py-3 text-sm outline-none placeholder:text-zinc-600"/><button className="rounded-xl bg-white px-4 py-2.5 text-sm font-medium text-black">Explore</button></div></div></div></section>
<section id="stories" className="mx-auto max-w-7xl px-5 pb-16 md:px-8"><div className="mb-6 flex items-end justify-between"><div><p className="text-sm text-amber-300">Start with a story</p><h2 className="mt-1 font-display text-3xl">Not another boring scripture app.</h2></div><button className="hidden items-center gap-1 text-sm text-zinc-400 sm:flex">View all <ChevronRight className="h-4 w-4"/></button></div><div className="scrollbar-hide mb-6 flex gap-2 overflow-x-auto pb-2">{filters.map(item=><button key={item} onClick={()=>setFilter(item)} className={`whitespace-nowrap rounded-full border px-4 py-2 text-sm ${filter===item?"border-white/20 bg-white text-black":"border-white/10 bg-white/5 text-zinc-400"}`}>{item}</button>)}</div><div className="grid gap-5 md:grid-cols-2">{visible.map(story=><article key={story.title} className={`story-card glass rounded-3xl bg-gradient-to-br ${story.accent} p-6`}><div className="flex items-start justify-between"><div className="rounded-2xl border border-white/10 bg-black/20 p-3">{story.icon}</div><div className="flex items-center gap-1.5 text-xs text-zinc-500"><Clock3 className="h-3.5 w-3.5"/>{story.duration}</div></div><div className="mt-8"><div className="mb-2 text-xs uppercase tracking-[0.18em] text-zinc-500">{story.tag}</div><h3 className="font-display text-2xl">{story.title}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-zinc-400">{story.subtitle}</p></div><div className="mt-6 flex items-center justify-between"><div className="rounded-full bg-black/20 px-3 py-1 text-xs text-zinc-400">{story.audience}</div><button className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-black"><Play className="h-4 w-4 fill-current"/>Listen</button></div></article>)}</div></section>
<section id="library" className="mx-auto grid max-w-7xl gap-5 px-5 pb-16 md:grid-cols-3 md:px-8"><Feature title="Read + Listen" icon={<Headphones className="h-5 w-5"/>} body="Verse-by-verse reading with synchronized narration, bookmarks, notes and family-friendly modes."/><Feature title="Sacred Places" icon={<MapPin className="h-5 w-5"/>} body="Explore temples, mosques, churches, monasteries, pilgrimage routes and places connected to stories."/><Feature title="Ask AI" icon={<Sparkles className="h-5 w-5"/>} body="Ask what the text says, what traditions interpret, what history records and what modern science can actually establish."/></section>
<section id="places" className="mx-auto max-w-7xl px-5 pb-16 md:px-8"><div className="glass rounded-3xl p-7 md:p-10"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-sm text-cyan-300">Explore the world behind the words</p><h2 className="mt-1 font-display text-3xl">Sacred places, local legends and living culture.</h2></div><button className="inline-flex items-center gap-2 text-sm text-zinc-400">Open atlas <ChevronRight className="h-4 w-4"/></button></div><div className="mt-8 grid gap-4 sm:grid-cols-3">{["Bodh Gaya","Varanasi","Sarnath"].map(place=><div key={place} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><MapPin className="h-5 w-5 text-cyan-300"/><div className="mt-8 font-display text-xl">{place}</div><p className="mt-1 text-sm text-zinc-500">Stories · history · traditions · nearby places</p></div>)}</div></div></section>
<section id="ai" className="mx-auto max-w-7xl px-5 pb-20 md:px-8"><div className="rounded-3xl border border-violet-300/10 bg-violet-300/[0.04] p-7 md:p-10"><div className="max-w-3xl"><p className="text-sm text-violet-300">Evidence-aware AI</p><h2 className="mt-2 font-display text-3xl">Four lenses. One answer panel.</h2><p className="mt-3 text-zinc-400">Scripture says what the text says. Tradition explains interpretation. Scholarship handles history and textual criticism. Science is reserved for empirical evidence.</p></div><div className="mt-8 grid gap-3 sm:grid-cols-4">{["Text","Tradition","Scholarship","Science"].map(l=><div key={l} className="rounded-2xl border border-white/10 bg-black/20 p-5"><div className="text-sm font-medium">{l}</div><div className="mt-2 text-xs leading-5 text-zinc-500">Source-cited, clearly labelled and kept distinct from the other lenses.</div></div>)}</div></div></section>
<footer className="border-t border-white/5 px-5 py-8 text-center text-xs text-zinc-600">Sacred Stories — an evidence-aware way to explore faith, heritage and human storytelling.</footer>
</main>}

function Feature({title,body,icon}:{title:string;body:string;icon:ReactNode}){return <div className="glass rounded-3xl p-6"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white/5">{icon}</div><h3 className="mt-6 font-display text-2xl">{title}</h3><p className="mt-2 text-sm leading-6 text-zinc-400">{body}</p></div>}