"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Bookmark, ChevronLeft, ChevronRight, Headphones, Pause, Play, Settings2 } from "lucide-react";

type Segment={id:string;sequence:number;startMs:number;endMs:number;storageKey?:string|null;transcript?:string|null};
export default function ReadingAudioPanel({title,segments,sourceText,onBookmark}:{title:string;segments:Segment[];sourceText:string;onBookmark?:(segment:Segment)=>void}){
 const audioRef=useRef<HTMLAudioElement>(null);const [playing,setPlaying]=useState(false);const [index,setIndex]=useState(0);const [rate,setRate]=useState(1);const current=segments[index];
 const textParts=useMemo(()=>sourceText.split(/(?<=[.!?।])\s+/),[sourceText]);
 useEffect(()=>{if(audioRef.current)audioRef.current.playbackRate=rate},[rate]);
 useEffect(()=>{const a=audioRef.current;if(!a)return;const onEnd=()=>{if(index<segments.length-1)setIndex(i=>i+1);else setPlaying(false)};a.addEventListener("ended",onEnd);return()=>a.removeEventListener("ended",onEnd)},[index,segments.length]);
 useEffect(()=>{const a=audioRef.current;if(!a)return;setPlaying(false);if(current?.storageKey){a.src=current.storageKey;a.load()}},[current]);
 const toggle=async()=>{const a=audioRef.current;if(!a||!current?.storageKey)return;if(a.paused){await a.play();setPlaying(true)}else{a.pause();setPlaying(false)}};
 return <section className="overflow-hidden rounded-3xl border border-white/10 bg-zinc-950 shadow-2xl"><div className="border-b border-white/10 bg-white/[0.03] px-5 py-4"><div className="flex items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-xs uppercase tracking-[.18em] text-zinc-500"><Headphones className="h-4 w-4"/> Read & listen</div><h2 className="mt-1 font-display text-xl font-semibold text-white">{title}</h2></div><div className="flex items-center gap-2"><button onClick={()=>setRate(r=>r===1?1.25:r===1.25?1.5:.75)} className="rounded-xl border border-white/10 px-3 py-2 text-xs text-zinc-300">{rate}×</button><button className="rounded-xl border border-white/10 p-2 text-zinc-300"><Settings2 className="h-4 w-4"/></button></div></div></div><div className="grid md:grid-cols-[1fr_360px]"><article className="max-h-[560px] overflow-y-auto p-6 md:p-8"><div className="prose prose-invert max-w-none leading-8 text-zinc-300">{textParts.map((p,i)=><p key={i} className={i===index?"rounded-xl bg-white/10 px-3 py-2 text-white transition-all":"px-3 py-2 text-zinc-400"}>{p}</p>)}</div></article><aside className="border-t border-white/10 bg-black/20 p-5 md:border-l md:border-t-0"><div className="mb-4 text-xs uppercase tracking-[.18em] text-zinc-600">Narration</div><div className="space-y-2">{segments.map((s,i)=><button key={s.id} onClick={()=>setIndex(i)} className={`w-full rounded-2xl border p-3 text-left ${i===index?"border-white/20 bg-white/10":"border-white/5 bg-white/[.02]"}`}><div className="flex items-center justify-between text-xs text-zinc-500"><span>Part {s.sequence}</span><span>{Math.max(1,Math.round((s.endMs-s.startMs)/1000))}s</span></div><p className="mt-1 line-clamp-2 text-sm text-zinc-300">{s.transcript}</p></button>)}</div></aside></div><div className="flex items-center gap-3 border-t border-white/10 p-4"><button disabled={index===0} onClick={()=>setIndex(i=>Math.max(0,i-1))} className="rounded-xl border border-white/10 p-3 disabled:opacity-30"><ChevronLeft className="h-5 w-5"/></button><button onClick={toggle} className="flex h-12 w-12 items-center justify-center rounded-full bg-white text-black disabled:opacity-40" disabled={!current?.storageKey}>{playing?<Pause className="h-5 w-5"/>:<Play className="ml-0.5 h-5 w-5"/>}</button><button disabled={index===segments.length-1} onClick={()=>setIndex(i=>Math.min(segments.length-1,i+1))} className="rounded-xl border border-white/10 p-3 disabled:opacity-30"><ChevronRight className="h-5 w-5"/></button><div className="min-w-0 flex-1"><div className="h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-white" style={{width:`${((index+1)/Math.max(segments.length,1))*100}%`}}/></div></div>{onBookmark&&current&&<button onClick={()=>onBookmark(current)} className="rounded-xl border border-white/10 p-3 text-zinc-300"><Bookmark className="h-5 w-5"/></button>}<audio ref={audioRef} preload="metadata"/></div></section>
}
