import type { CategoryKey } from "../../categories";

/**
 * Art direction per category, fixed in code so every cover in a category shares one look
 * and the image model is never left to guess the genre.
 */
export type CoverStyle={label:string;medium:string;palette:string;lighting:string;composition:string;avoid:string};

export type CoverStyleKey=CategoryKey|"scripture"|"adult";

/** Shared by every cover, so the whole library looks like one publisher's list. */
export const HOUSE_STYLE="Premium audiobook cover art: rich, painterly digital illustration with fine detail, depth and atmosphere, the finish of a bestselling published cover. Cohesive limited palette, strong value contrast, one clear focal point.";

const PEOPLE_HISTORICAL="If a real historical person appears, paint them as a stylised illustration in their era, shown from a distance, in profile, from behind or in silhouette rather than a close-up likeness.";

export const COVER_STYLES:Record<CoverStyleKey,CoverStyle>={
  epics:{label:"epic / legend",medium:"Majestic painterly illustration with mythic scale. Take art influences from the story's own culture: Indian miniature and temple-mural detail for Indian epics, fresco and red-figure tones for Greek myths, carved-wood and runic textures for Norse and Finnish sagas, Mesopotamian relief motifs for Gilgamesh.",palette:"deep golds, burnt orange, crimson and midnight blue",lighting:"dramatic golden-hour or storm light breaking through clouds",composition:"heroic low angle, figure or symbol set against a vast sky or landscape",avoid:"gore, severed limbs, modern objects"},
  mythology:{label:"mythology",medium:"Painterly mythic illustration rooted in the culture of origin, with traditional iconography and ornament.",palette:"jewel tones: saffron, lapis, emerald, gold",lighting:"luminous, otherworldly glow",composition:"central divine or symbolic figure, framed by nature or architecture",avoid:"disrespectful or sexualised depictions of deities"},
  children:{label:"children's story",medium:"Warm, friendly picture-book illustration with soft rounded shapes and gentle gouache and watercolour textures; expressive, kind faces; animals drawn with charm.",palette:"bright, cheerful and soft: sunny yellow, sky blue, leaf green, coral",lighting:"soft, even daylight or a cosy warm glow",composition:"simple, uncluttered scene with one lovable main character",avoid:"anything scary, sharp teeth, weapons, danger or sadness shown graphically"},
  festivals:{label:"festival story",medium:"Joyful, luminous celebration illustration: lamps, lanterns, flowers, colour and light, with crowds suggested as soft shapes. Every detail true to the specific festival and region.",palette:"the festival's own colours, glowing against a deep evening sky",lighting:"warm points of light (diyas, lanterns, candles, fireworks) with soft bloom",composition:"a festive focal object or small group in the lower half, light rising into the sky above",avoid:"generic party imagery or mixing symbols from different festivals"},
  adventure:{label:"adventure",medium:"Classic adventure-novel cover painting with a sense of journey and discovery.",palette:"ocean teal, sand, sunset orange and deep green",lighting:"bright adventurous light with long shadows",composition:"dynamic diagonal; a small determined figure facing a vast landscape, ship, map or mysterious destination",avoid:"modern technology unless the story has it"},
  "moral-tales":{label:"moral tale",medium:"Storybook fable illustration, simple and symbolic, with timeless folk-art warmth.",palette:"gentle earthy tones with one warm accent colour",lighting:"soft morning light",composition:"one clear symbolic moment (an animal, a choice, an object) in a simple setting",avoid:"clutter, violence"},
  parables:{label:"parable",medium:"Contemplative, symbolic storybook illustration with the calm of a wisdom tale.",palette:"muted natural tones: ochre, olive, stone, sky",lighting:"quiet, clear light",composition:"minimal scene built around a single meaningful image (a seed, a lamp, a path, a cup)",avoid:"busy backgrounds"},
  folklore:{label:"folk tale",medium:"Textured illustration inspired by the region's traditional folk art (patterns, motifs and craft techniques of that culture) with storyteller warmth.",palette:"hand-dyed natural pigments: indigo, madder red, turmeric, forest green",lighting:"firelight or dusky village light",composition:"a village, forest or river scene with the tale's key creature or object",avoid:"mixing motifs from unrelated cultures"},
  ghost:{label:"ghost story",medium:"Atmospheric, moody painterly illustration: fog, moonlight and long suggestive shadows. Mysterious rather than gory.",palette:"cold blues, slate greys and sickly green, with one warm lamp or window glow",lighting:"moonlight and a single lantern or window",composition:"an old tree, ruin, road or house dominating the frame, with a faint presence implied, not shown in detail",avoid:"blood, gore, demonic or screaming faces, jump-scare imagery"},
  biographies:{label:"biography of a great life",medium:`Dignified, warm portrait-style painting set in the person's era and place, with symbols of their work around them. ${PEOPLE_HISTORICAL}`,palette:"warm umber, gold and soft blue",lighting:"hopeful, warm side light",composition:"the person or their emblematic object in the lower two-thirds, the setting of their life behind",avoid:"photorealistic likeness, modern clothing out of era"},
  "sacred-places":{label:"holy place",medium:"Reverent architectural landscape painting of the actual place, with accurate architecture and setting; pilgrims as small silhouettes; a sense of awe and peace.",palette:"dawn or golden-hour tones: rose, gold and soft blue",lighting:"sunrise or sunset light on the architecture",composition:"the shrine, temple, mountain or river as the hero, seen from a respectful distance",avoid:"tourist crowds, signage, inaccurate architecture"},
  historical:{label:"history",medium:`Historical oil-painting style with period-accurate costume, architecture and objects. ${PEOPLE_HISTORICAL}`,palette:"rich oil tones: sienna, deep green and parchment",lighting:"dramatic chiaroscuro",composition:"a decisive moment or emblematic object of the event, in its real setting",avoid:"anachronisms, gore"},
  inspirational:{label:"inspiring story",medium:`Uplifting painterly illustration about perseverance and hope. ${PEOPLE_HISTORICAL}`,palette:"sunrise gradient: peach, gold and clear blue",lighting:"breaking dawn light",composition:"a figure or symbol rising or moving toward the light",avoid:"clichéd stock-photo poses"},
  "war-courage":{label:"story of courage",medium:"Solemn, heroic painting about courage and resolve rather than violence: flags, landscapes, silhouettes and the aftermath of struggle.",palette:"smoky greys and earth tones with a single heroic accent colour",lighting:"light breaking through smoke or cloud",composition:"a resolute figure or group in silhouette against a dramatic sky",avoid:"blood, gore, graphic combat, dead bodies, glorifying violence"},
  survival:{label:"survival story",medium:"Cinematic survival painting: a vast, harsh environment (ice, sea, desert, mountain or jungle) dwarfing a lone determined figure.",palette:"the environment's own palette, cold or scorched, with a small warm point of hope",lighting:"harsh natural light or a storm clearing",composition:"tiny figure, immense landscape, a strong horizon",avoid:"injury detail, gore"},
  "friendship-family":{label:"family and friendship story",medium:"Warm, intimate illustration of connection and belonging, with gentle expressions and natural gestures.",palette:"cosy amber, rose and soft green",lighting:"soft golden afternoon light",composition:"two or three figures close together, or a meaningful shared object",avoid:"forced, staged poses"},
  romance:{label:"love story",medium:"Elegant classic romance-novel cover painting: two figures in period-accurate clothing in a tender, wistful atmosphere. Tasteful, fully clothed.",palette:"rose, deep wine, gold and twilight blue",lighting:"soft romantic dusk or candle light",composition:"two figures in a meaningful setting, emotion carried by gaze and gesture",avoid:"nudity, sexual content, suggestive poses"},
  rituals:{label:"tradition and ritual",medium:"Serene ceremonial illustration or still life: sacred objects (lamps, incense, flowers, water, thread, bread, candles) rendered with reverence and accuracy to the tradition.",palette:"warm candle tones on a deep, calm background",lighting:"soft directional light, as from a lamp or window",composition:"close, centred arrangement of the ritual's key objects, with hands at most",avoid:"mixing objects from different traditions"},
  crime:{label:"mystery",medium:"Noir mystery cover painting: strong shadows, a single clue object or a figure in silhouette, intrigue through composition.",palette:"limited palette of near-black, deep blue and one accent colour",lighting:"hard, low-key light with deep shadows",composition:"a single clue or doorway as the focal point, plenty of negative space",avoid:"gore, crime-scene bodies"},
  thriller:{label:"thriller",medium:"High-tension cinematic cover painting with bold contrast and dramatic perspective.",palette:"high-contrast dark tones with a hot accent (orange or red)",lighting:"stark rim light",composition:"steep perspective, with the figure or object caught at a moment of tension",avoid:"gore, weapons aimed at the viewer"},
  stories:{label:"story",medium:"Classic storybook cover painting that captures the story's heart in one image.",palette:"harmonious palette suited to the story's mood",lighting:"atmospheric, flattering light",composition:"one clear focal subject in a simple setting",avoid:"clutter"},
  scripture:{label:"sacred text",medium:"Reverent, contemplative symbolic painting (light, landscape, sacred architecture, an open manuscript, natural symbols); dignified and timeless.",palette:"gold leaf, ivory, deep blue and warm stone",lighting:"soft divine light, as through a window or across a dawn landscape",composition:"a single sacred symbol or landscape, with generous calm space",avoid:"depicting God, sensational imagery"},
  adult:{label:"mature love story for adults",medium:"Elegant, classic literary romance cover painting: two adults in period-accurate clothing; longing and tension conveyed through gaze, light and setting. Tasteful and fully clothed.",palette:"deep wine, rose gold, candlelight and shadow",lighting:"low, warm candle or dusk light",composition:"two figures, or a single evocative object (a letter, a rose, an open window), in a period setting",avoid:"nudity, lingerie, sexual acts or poses, anyone who looks under 18"},
};

/** Content from these traditions is not depicted figuratively when it involves prophets or holy persons. */
const ANICONIC=/\b(islam|islamic|muslim|sufi|quran|qur'?an|prophet muhammad|muhammad|ramadan|eid|hajj|umrah|mecca|makkah|medina|madinah|ka'?ba|mosque|masjid|bilal)\b/i;
export function needsAniconicArt(...texts:string[]){return ANICONIC.test(texts.join(" "))}

export const ANICONIC_RULE="Islamic content: do not depict the Prophet Muhammad, any prophet, angel or God, even veiled or faceless. Tell the story through architecture, landscape, light, objects, calligraphy-free geometric patterns, and ordinary people seen from behind or far away.";
